---
title: "pml_cpw"
author: "Dhruv K Pant"
date: "June 18, 2014"
output: html_document
---
## TITLE 
### Summary 

### Read in input data 
```{r input_data,cache=TRUE}
tr <- read.csv("pml-training.csv")
te <- read.csv("pml-testing.csv")
```

### Explore the data
```{r exploration}
str(tr); dim(tr)
colnames(tr)
table(tr$classe)

```

### Identifying NA's 
```{r remove_na_training,cache=T}
cols.w.nas <- apply(tr,2,function(x) sum(is.na(x)))
### Remove columns which have high percentage of NAs
cols.to.remove <- names(cols.w.nas[cols.w.nas>0])
tr2 <- tr[,!colnames(tr)%in%cols.to.remove]
### keep variables pertaining to belt/forearm/arm/dumbbell
ind1 <- grepl("_arm|_forearm|_dumbbell|_belt",colnames(tr2))
tr3 <- cbind(tr2[,ind1],classe=tr2$classe)
ind2 <- !grepl("yaw",colnames(tr3))
#tr4 <- tr3[,ind2]
#x <- head(tr4,n=100)
cn.tr <- colnames(tr3)

```

```{r remove_na_testing,cache=T}
cols.w.nas <- apply(te,2,function(x) sum(is.na(x)))
cols.to.remove <- names(cols.w.nas[cols.w.nas>0])
te2 <- te[,!colnames(te)%in%cols.to.remove]
ind1 <- grepl("_arm|_forearm|_dumbbell|_belt",colnames(te2))
te3 <- cbind(te2[,ind1],problem_id=te2$problem_id)
cn.te <- colnames(te3)

common <- intersect(cn.tr,cn.te)
```

### Explore correlation among variables
``` {r corr}
x <- cor(subset(tr4,select=-classe))
diag(x) <- 0
which(abs(x)>0.8,arr.ind=T)

```

### Variable selection
``` {r variable_selection}
tr4 <- cbind(tr3[,colnames(tr3)%in%common],classe=tr3$classe)
te4 <- cbind(te3[,colnames(te3)%in%common],problem_id=te3$problem_id)

```

### Preprocess the data 
```{r preprocess, cache=TRUE}
### center and scale, Box-Cox??
require(caret)
set.seed(12365)
mod.rpart.scaled <- train(classe~., data=tr4,preProcess=c("center","scale"),method="rpart")
mod.rpart <- train(classe~., data=tr4,method="rpart")

predict(mod.rpart.scaled,te4)
### assess variable importance from the rpart models ###
### and consider only those variables for the RF and boosting models 
mod.rf <- train(classe~., data=tr4,method="rf",trControl=trainControl(method="cv"),number=3)
mod.gbm <- train(classe~., data=tr4,method="gbm",verbose=F)   ### takes v long

mod.rf.oob <- train(classe~., data=tr4,method="rf",trControl=trainControl(method="oob"),number=3)
```


### Fit Models 
```{r models}
#glm <- train(classe~., method="glm",preProcess="pca",data=tr2)
```

You can also embed plots, for example:

```{r, echo=FALSE}
#plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
